version: '3'
services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:cached
    ports:
      - 54320:5432

volumes:
  db-data:
    driver: local
